osx_image: xcode8.2
language: objective-c
xcode_project: STSecurity.xcodeproj
xcode_sdk: iphonesimulator
xcode_scheme: STSecurity
env:
    - TRAVIS_XCODE_DESTINATION="platform=iOS Simulator,name=iPhone 6,OS=9.3"
branches:
    only:
        - master
before_script:
    - gem install xcpretty
script: xcodebuild test -project "${TRAVIS_XCODE_PROJECT}" -scheme "${TRAVIS_XCODE_SCHEME}" -sdk "${TRAVIS_XCODE_SDK}" -destination "${TRAVIS_XCODE_DESTINATION}" | xcpretty
