language: objective-c
branches:
    only:
        - master
before_install:
    - bundle install --path .bundle
before_script:
    - bundle exec rake -s analyze:${CI_PLATFORM}
script: bundle exec rake -s test:${CI_PLATFORM}
env:
    - CI_PLATFORM=ios
